### PR TITLE
(docs) Wait for ipfs ready event for #10

### PR DESCRIPTION
**Pull request by rjharmon**
This example doesn't quite work as-is, but it gets past the most basic issue of having ipfs service be ready.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks, @rjharmon! What would be needed to make this work as is?

**Comment by rjharmon** [comment]
This works for me if I don't try to create the orbitdb/ directory with the cli tool (see https://github.com/orbitdb/orbit-db-cli/issues/16)

**Comment by shamb0t** [comment]
Thanks @rjharmon! Does the example work if you set the pubsub flag in the options?
`const ipfs = new IPFS({ repo: 'orbitdb/ipfs' , EXPERIMENTAL: { pubsub : true }})`

**Comment by rjharmon** [comment]
@shamb0t sorry, I thought I captured that.  Updated.

I've tried getting these data back on a subsequent run of same example code, without success as yet.  It would be nice to have such an example posting data increments so people can see something of a bit higher value.

**Comment by aphelionz** [comment]
Closing this as it's now out of date and the README has since been updated

**Pull request closed without merging**
